<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXGcOIZG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXGcOIZG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXGcOIZG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXGcOIZG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXGcOIZG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XGcOIZG',
    'container.build_id' => 'db7ca0d5',
    'container.build_time' => 1573557834,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXGcOIZG');
