<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLmRtlB3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLmRtlB3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLmRtlB3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLmRtlB3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLmRtlB3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LmRtlB3',
    'container.build_id' => '1ab18289',
    'container.build_time' => 1574364081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLmRtlB3');
